### PR TITLE
One click api

### PR DESCRIPTION
**Pull request by dtjanaka**
Add route to API for one click publishing
Add a password change system for admins for one click publishing
Overhaul admin system
- New role: superadmin
- Superadmins can manage admins (add, remove) and reassign another admin as superadmin (replacing themself)
- Based on Google login (admins don't all have to use same credentials now)

General polish
Prettier for whole codebase : )

### CODE REVIEW

**Comment by dtjanaka** [comment]
https://github.com/uclaacm/membership-portal-ui/pull/103

**Review by advaithg — APPROVED** [review]
Is a giant PR, but I think overall looks good - not sure if I missed anything though so might wait for matt / nhi's review!

**Comment by matthewcn56** [comment]
Yep will take a look today!

**Comment by matthewcn56** [comment]
I'll still look over this today though!

**Comment by matthewcn56** [comment]
If necessary i'll add some comments here

**Pull request merged**
