### PR TITLE
Made Leaderboard API send more information including activity

### PR DESCRIPTION
**Pull request by alexanderqchen**
I added uuid, picture, year, major, activity to Leaderboard API. This would allow the leaderboard to display more detailed information about each user. I also changed the leaderboard API to also only obtain public user data rather than all user data. I also merged this branch with the dummy data branch created by @helenhyewonlee .

### CODE REVIEW

**Comment by alexanderqchen** [comment]
When testing to see if activity data was available, I created a dummy account and was able to view data for that account, but I didn't see any activity for the other users. Was I supposed to run something in order to load Helen's data?

**Comment by nkansal96** [comment]
You needed to hit the setup endpoint again in order to load Helen's data.

**Comment by nkansal96** [comment]
Also you need to pull and merge from helenhyewonlee/event-timeseries since you don't have the latest changes on this branch

**Comment by alexanderqchen** [comment]
Sorry for the late reply, but I talked to Helen about loading the dummy data, but we couldn't figure out what was going wrong. In order to "hit the setup endpoint", I just went to "http://localhost:8080/app/api/v1/health/setup" in my browser. After checking the database, however, I did not see any data in the activity table. Is there something else I need to do for setup?

**Comment by alexanderqchen** [comment]
I'm going to close this PR because it's a little too old. It would probably be easier just to redo all of this.

**Pull request closed without merging**
